import React, { useState } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Button } from '../ui/button';
import { LoadingSpinner } from '../ui/loading-spinner';
import { ArrowLeft, FileText, Save, X, RotateCcw } from 'lucide-react';
import { SalesQuotationHeader } from './SalesQuotationHeader';
import { SalesQuotationItemsTable } from './SalesQuotationItemsTable';
import { SalesQuotationSummary } from './SalesQuotationSummary';
import { SalesQuotationRecents } from './SalesQuotationRecents';
import { SalesQuotation, SalesQuotationItem } from '../../types/sales';
import { useCreateSalesQuotation } from '../../hooks/useSalesData';

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      retry: 1,
      staleTime: 30000,
    },
  },
});

interface QuotationFormData {
  customerName: string;
  customerCode: string;
  contactPerson: string;
  postingDate: string;
  documentDate: string;
  validUntil: string;
  shipTo: string;
  billTo: string;
  items: SalesQuotationItem[];
  salesEmployee: string;
  remarks: string;
  discountType: 'percentage' | 'amount';
  discountValue: number;
}

const SalesQuotationCreationContent: React.FC = () => {
  const createQuotationMutation = useCreateSalesQuotation();
  
  const [formData, setFormData] = useState<QuotationFormData>({
    customerName: '',
    customerCode: '',
    contactPerson: '',
    postingDate: new Date().toISOString().split('T')[0],
    documentDate: new Date().toISOString().split('T')[0],
    validUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 30 days from now
    shipTo: '',
    billTo: '',
    items: [],
    salesEmployee: '',
    remarks: '',
    discountType: 'percentage',
    discountValue: 0,
  });

  const handleBack = () => {
    console.log('Navigate back to quotation list');
  };

  const calculateTotals = () => {
    const subtotal = formData.items
      .filter(item => !item.taxOnly)
      .reduce((sum, item) => sum + item.total, 0);
    
    const discountAmount = formData.discountType === 'percentage' 
      ? (subtotal * formData.discountValue / 100)
      : formData.discountValue;
    
    // Calculate tax amount (simplified - would need proper tax calculation logic)
    const taxAmount = formData.items.reduce((sum, item) => {
      // This is a simplified tax calculation
      return sum + (item.total * 0.125); // Assuming 12.5% VAT for demo
    }, 0);
    
    const total = (subtotal - discountAmount) + taxAmount;
    
    return { subtotal, discountAmount, taxAmount, total };
  };

  const handleSave = async (action: 'save' | 'save-close' | 'save-new') => {
    const { subtotal, discountAmount, taxAmount, total } = calculateTotals();
    
    const quotationData: Omit<SalesQuotation, 'id' | 'createdAt' | 'updatedAt'> = {
      documentNo: `SQ-${Date.now()}`, // Would be generated by backend
      customerName: formData.customerName,
      customerCode: formData.customerCode,
      contactPerson: formData.contactPerson,
      postingDate: formData.postingDate,
      documentDate: formData.documentDate,
      validUntil: formData.validUntil,
      shipTo: formData.shipTo,
      billTo: formData.billTo,
      status: 'Draft',
      items: formData.items,
      salesEmployee: formData.salesEmployee,
      remarks: formData.remarks,
      subtotal,
      discountType: formData.discountType,
      discountValue: formData.discountValue,
      discountAmount,
      taxAmount,
      total,
    };

    try {
      await createQuotationMutation.mutateAsync(quotationData);
      
      switch (action) {
        case 'save-close':
          console.log('Save and navigate back to list');
          break;
        case 'save-new':
          handleClear();
          break;
        default:
          console.log('Quotation saved');
      }
    } catch (error) {
      console.error('Failed to save quotation:', error);
    }
  };

  const handleClear = () => {
    setFormData({
      customerName: '',
      customerCode: '',
      contactPerson: '',
      postingDate: new Date().toISOString().split('T')[0],
      documentDate: new Date().toISOString().split('T')[0],
      validUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      shipTo: '',
      billTo: '',
      items: [],
      salesEmployee: '',
      remarks: '',
      discountType: 'percentage',
      discountValue: 0,
    });
  };

  const totals = calculateTotals();

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <Button variant="ghost" onClick={handleBack} className="p-2">
                <ArrowLeft className="h-5 w-5" />
              </Button>
              <div className="flex items-center space-x-3">
                <div className="p-2 bg-blue-100 rounded-lg">
                  <FileText className="h-6 w-6 text-blue-600" />
                </div>
                <div>
                  <h1 className="text-2xl font-bold text-gray-900">Create Sales Quotation</h1>
                  <p className="text-gray-600">Prepare a new quotation for customer</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
          {/* Main Content */}
          <div className="lg:col-span-3 space-y-6">
            {/* Header Fields */}
            <SalesQuotationHeader
              formData={formData}
              onFormDataChange={setFormData}
            />

            {/* Items Table */}
            <SalesQuotationItemsTable
              items={formData.items}
              onItemsChange={(items) => setFormData({ ...formData, items })}
            />

            {/* Additional Fields */}
            <Card>
              <CardHeader>
                <CardTitle>Additional Information</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <label className="text-sm font-medium text-gray-700 mb-2 block">
                    Sales Employee
                  </label>
                  <select
                    value={formData.salesEmployee}
                    onChange={(e) => setFormData({ ...formData, salesEmployee: e.target.value })}
                    className="w-full p-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  >
                    <option value="">Select sales employee...</option>
                    <option value="John Mensah">John Mensah</option>
                    <option value="Sarah Asante">Sarah Asante</option>
                    <option value="Michael Osei">Michael Osei</option>
                    <option value="Grace Adjei">Grace Adjei</option>
                  </select>
                </div>
                
                <div>
                  <label className="text-sm font-medium text-gray-700 mb-2 block">
                    Remarks
                  </label>
                  <textarea
                    value={formData.remarks}
                    onChange={(e) => setFormData({ ...formData, remarks: e.target.value })}
                    rows={3}
                    className="w-full p-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                    placeholder="Add any additional remarks or notes..."
                  />
                </div>
              </CardContent>
            </Card>

            {/* Footer Actions */}
            <Card>
              <CardContent className="pt-6">
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-3">
                    <Button variant="outline" onClick={handleClear}>
                      <RotateCcw className="h-4 w-4 mr-2" />
                      Clear
                    </Button>
                    <Button variant="outline" onClick={handleBack}>
                      <X className="h-4 w-4 mr-2" />
                      Cancel
                    </Button>
                  </div>
                  
                  <div className="flex items-center space-x-2">
                    <div className="relative">
                      <Button
                        onClick={() => handleSave('save')}
                        disabled={createQuotationMutation.isPending}
                        className="bg-blue-600 hover:bg-blue-700"
                      >
                        {createQuotationMutation.isPending ? (
                          <>
                            <LoadingSpinner size="sm" className="mr-2" />
                            Saving...
                          </>
                        ) : (
                          <>
                            <Save className="h-4 w-4 mr-2" />
                            Save
                          </>
                        )}
                      </Button>
                    </div>
                    <Button
                      variant="outline"
                      onClick={() => handleSave('save-close')}
                      disabled={createQuotationMutation.isPending}
                    >
                      Save & Close
                    </Button>
                    <Button
                      variant="outline"
                      onClick={() => handleSave('save-new')}
                      disabled={createQuotationMutation.isPending}
                    >
                      Save & New
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Sidebar */}
          <div className="lg:col-span-1 space-y-6">
            {/* Summary */}
            <SalesQuotationSummary
              subtotal={totals.subtotal}
              discountType={formData.discountType}
              discountValue={formData.discountValue}
              discountAmount={totals.discountAmount}
              taxAmount={totals.taxAmount}
              total={totals.total}
              onDiscountChange={(type, value) => 
                setFormData({ ...formData, discountType: type, discountValue: value })
              }
            />

            {/* Recent Quotations */}
            <SalesQuotationRecents />
          </div>
        </div>
      </div>
    </div>
  );
};

export const SalesQuotationCreationPage: React.FC = () => {
  return (
    <QueryClientProvider client={queryClient}>
      <SalesQuotationCreationContent />
    </QueryClientProvider>
  );
};