import React, { useState } from 'react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Button } from '../ui/button';
import { LoadingSpinner } from '../ui/loading-spinner';
import { ArrowLeft, ShoppingCart, Save, X, RotateCcw, Copy, Download } from 'lucide-react';
import { SalesOrderHeader } from './SalesOrderHeader';
import { SalesOrderItemsTable } from './SalesOrderItemsTable';
import { SalesOrderSummary } from './SalesOrderSummary';
import { SalesOrderRecents } from './SalesOrderRecents';
import { PaymentMeansPanel } from './PaymentMeansPanel';
import { CopyFromDialog } from './CopyFromDialog';
import { SalesOrder, SalesOrderItem, CopyMode, DocumentType, PaymentMeans } from '../../types/sales';
import { useCreateSalesOrder, useSalesQuotation } from '../../hooks/useSalesData';
import { convertPrice, exchangeRates } from '../../api/salesData';

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      retry: 1,
      staleTime: 30000,
    },
  },
});

interface OrderFormData {
  customerName: string;
  customerCode: string;
  contactPerson: string;
  postingDate: string;
  documentDate: string;
  requestedDeliveryDate: string;
  shipTo: string;
  billTo: string;
  items: SalesOrderItem[];
  salesEmployee: string;
  remarks: string;
  discountType: 'percentage' | 'amount';
  discountValue: number;
  parentModule?: string;
  parentModuleId?: string;
  currency: string;
  exchangeRate: number;
  paymentMeans?: PaymentMeans;
}

const SalesOrderCreationContent: React.FC = () => {
  const createOrderMutation = useCreateSalesOrder();
  const [showCopyFromDialog, setShowCopyFromDialog] = useState(false);
  
  const [formData, setFormData] = useState<OrderFormData>({
    customerName: '',
    customerCode: '',
    contactPerson: '',
    postingDate: new Date().toISOString().split('T')[0],
    documentDate: new Date().toISOString().split('T')[0],
    requestedDeliveryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 7 days from now
    shipTo: '',
    billTo: '',
    items: [],
    salesEmployee: '',
    remarks: '',
    discountType: 'percentage',
    discountValue: 0,
    currency: 'GHS',
    exchangeRate: 1.0,
  });

  const handleBack = () => {
    console.log('Navigate back to order list');
  };

  const calculateTotals = () => {
    // Convert item totals to current currency if needed
    const subtotal = formData.items
      .filter(item => !item.taxOnly)
      .reduce((sum, item) => sum + item.total, 0);
    
    const discountAmount = formData.discountType === 'percentage' 
      ? (subtotal * formData.discountValue / 100)
      : formData.discountValue;
    
    // Calculate tax amount (simplified - would need proper tax calculation logic)
    const taxAmount = formData.items.reduce((sum, item) => {
      // This is a simplified tax calculation
      return sum + (item.total * 0.125); // Assuming 12.5% VAT for demo
    }, 0);
    
    const total = (subtotal - discountAmount) + taxAmount;
    
    return { subtotal, discountAmount, taxAmount, total };
  };

  const handleCurrencyChange = (newCurrency: string) => {
    const oldCurrency = formData.currency;
    if (oldCurrency === newCurrency) return;

    const oldRate = exchangeRates[oldCurrency] || 1.0;
    const newRate = exchangeRates[newCurrency] || 1.0;
    const conversionFactor = newRate / oldRate;

    // Convert all item prices
    const updatedItems = formData.items.map(item => ({
      ...item,
      unitPrice: item.unitPrice * conversionFactor,
      total: item.total * conversionFactor,
    }));

    // Convert discount value if it's an amount
    const updatedDiscountValue = formData.discountType === 'amount' 
      ? formData.discountValue * conversionFactor 
      : formData.discountValue;

    setFormData(prev => ({
      ...prev,
      currency: newCurrency,
      exchangeRate: newRate,
      items: updatedItems,
      discountValue: updatedDiscountValue,
    }));
  };

  const handleSave = async (action: 'save' | 'save-close' | 'save-new') => {
    const { subtotal, discountAmount, taxAmount, total } = calculateTotals();
    
    const orderData: Omit<SalesOrder, 'id' | 'createdAt' | 'updatedAt'> = {
      documentNo: `SO-${Date.now()}`, // Would be generated by backend
      customerName: formData.customerName,
      customerCode: formData.customerCode,
      contactPerson: formData.contactPerson,
      postingDate: formData.postingDate,
      documentDate: formData.documentDate,
      requestedDeliveryDate: formData.requestedDeliveryDate,
      shipTo: formData.shipTo,
      billTo: formData.billTo,
      status: 'Open',
      items: formData.items,
      salesEmployee: formData.salesEmployee,
      remarks: formData.remarks,
      subtotal,
      discountType: formData.discountType,
      discountValue: formData.discountValue,
      discountAmount,
      taxAmount,
      total,
      parentModule: formData.parentModule,
      parentModuleId: formData.parentModuleId,
      currency: formData.currency,
      exchangeRate: formData.exchangeRate,
      paymentMeans: formData.paymentMeans,
    };

    try {
      await createOrderMutation.mutateAsync(orderData);
      
      switch (action) {
        case 'save-close':
          console.log('Save and navigate back to list');
          break;
        case 'save-new':
          handleClear();
          break;
        default:
          console.log('Order saved');
      }
    } catch (error) {
      console.error('Failed to save order:', error);
    }
  };

  const handleClear = () => {
    setFormData({
      customerName: '',
      customerCode: '',
      contactPerson: '',
      postingDate: new Date().toISOString().split('T')[0],
      documentDate: new Date().toISOString().split('T')[0],
      requestedDeliveryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      shipTo: '',
      billTo: '',
      items: [],
      salesEmployee: '',
      remarks: '',
      discountType: 'percentage',
      discountValue: 0,
      currency: 'GHS',
      exchangeRate: 1.0,
    });
  };

  const handleCopyFrom = async (sourceType: DocumentType, sourceId: string, mode: CopyMode) => {
    try {
      // In a real app, you'd fetch the source document data
      // For now, we'll simulate copying from a quotation
      if (sourceType === 'sales-quotation') {
        // Simulate fetching quotation data and copying it
        console.log(`Copying from ${sourceType} ${sourceId} in ${mode} mode`);
        
        // This would be replaced with actual data fetching
        const mockCopiedData = {
          customerName: 'Akosua Trading Co.',
          customerCode: 'CUST001',
          contactPerson: 'Akosua Mensah',
          shipTo: '12 Market Street, Kumasi',
          billTo: '12 Market Street, Kumasi',
          salesEmployee: 'John Mensah',
          remarks: 'Copied from Sales Quotation',
          parentModule: 'sales quotation',
          parentModuleId: sourceId,
          currency: 'GHS', // Will be updated when customer is selected
          exchangeRate: 1.0,
        };
        
        setFormData(prev => ({
          ...prev,
          ...mockCopiedData,
        }));
      }
    } catch (error) {
      console.error('Failed to copy document:', error);
    }
  };

  const totals = calculateTotals();

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <Button variant="ghost" onClick={handleBack} className="p-2">
                <ArrowLeft className="h-5 w-5" />
              </Button>
              <div className="flex items-center space-x-3">
                <div className="p-2 bg-green-100 rounded-lg">
                  <ShoppingCart className="h-6 w-6 text-green-600" />
                </div>
                <div>
                  <h1 className="text-2xl font-bold text-gray-900">Create Sales Order</h1>
                  <p className="text-gray-600">Prepare a new order for customer</p>
                </div>
              </div>
            </div>
            <Button
              variant="outline"
              onClick={() => setShowCopyFromDialog(true)}
              className="flex items-center space-x-2"
            >
              <Download className="h-4 w-4" />
              <span>Copy From</span>
            </Button>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
          {/* Main Content */}
          <div className="lg:col-span-3 space-y-6">
            {/* Header Fields */}
            <SalesOrderHeader
              formData={formData}
              onFormDataChange={setFormData}
              onCurrencyChange={handleCurrencyChange}
            />

            {/* Items Table */}
            <SalesOrderItemsTable
              items={formData.items}
              onItemsChange={(items) => setFormData({ ...formData, items })}
              showOriginalQuantity={!!formData.parentModule}
              currency={formData.currency}
            />

            {/* Additional Fields */}
            <Card>
              <CardHeader>
                <CardTitle>Additional Information</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <label className="text-sm font-medium text-gray-700 mb-2 block">
                    Sales Employee
                  </label>
                  <select
                    value={formData.salesEmployee}
                    onChange={(e) => setFormData({ ...formData, salesEmployee: e.target.value })}
                    className="w-full p-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-green-500 focus:border-green-500"
                  >
                    <option value="">Select sales employee...</option>
                    <option value="John Mensah">John Mensah</option>
                    <option value="Sarah Asante">Sarah Asante</option>
                    <option value="Michael Osei">Michael Osei</option>
                    <option value="Grace Adjei">Grace Adjei</option>
                  </select>
                </div>
                
                <div>
                  <label className="text-sm font-medium text-gray-700 mb-2 block">
                    Remarks
                  </label>
                  <textarea
                    value={formData.remarks}
                    onChange={(e) => setFormData({ ...formData, remarks: e.target.value })}
                    rows={3}
                    className="w-full p-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-green-500 focus:border-green-500"
                    placeholder="Add any additional remarks or notes..."
                  />
                </div>

                {/* Show parent document info if copied */}
                {formData.parentModule && formData.parentModuleId && (
                  <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg">
                    <p className="text-sm text-blue-800">
                      <strong>Copied from:</strong> {formData.parentModule} ({formData.parentModuleId})
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Footer Actions */}
            <Card>
              <CardContent className="pt-6">
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-3">
                    <Button variant="outline" onClick={handleClear}>
                      <RotateCcw className="h-4 w-4 mr-2" />
                      Clear
                    </Button>
                    <Button variant="outline" onClick={handleBack}>
                      <X className="h-4 w-4 mr-2" />
                      Cancel
                    </Button>
                  </div>
                  
                  <div className="flex items-center space-x-2">
                    <div className="relative">
                      <Button
                        onClick={() => handleSave('save')}
                        disabled={createOrderMutation.isPending}
                        className="bg-green-600 hover:bg-green-700"
                      >
                        {createOrderMutation.isPending ? (
                          <>
                            <LoadingSpinner size="sm" className="mr-2" />
                            Saving...
                          </>
                        ) : (
                          <>
                            <Save className="h-4 w-4 mr-2" />
                            Save
                          </>
                        )}
                      </Button>
                    </div>
                    <Button
                      variant="outline"
                      onClick={() => handleSave('save-close')}
                      disabled={createOrderMutation.isPending}
                    >
                      Save & Close
                    </Button>
                    <Button
                      variant="outline"
                      onClick={() => handleSave('save-new')}
                      disabled={createOrderMutation.isPending}
                    >
                      Save & New
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Sidebar */}
          <div className="lg:col-span-1 space-y-6">
            {/* Summary */}
            <SalesOrderSummary
              subtotal={totals.subtotal}
              discountType={formData.discountType}
              discountValue={formData.discountValue}
              discountAmount={totals.discountAmount}
              taxAmount={totals.taxAmount}
              total={totals.total}
              currency={formData.currency}
              onDiscountChange={(type, value) => 
                setFormData({ ...formData, discountType: type, discountValue: value })
              }
            />

            {/* Payment Means */}
            <PaymentMeansPanel
              paymentMeans={formData.paymentMeans}
              onPaymentMeansChange={(paymentMeans) => 
                setFormData({ ...formData, paymentMeans })
              }
              totalAmount={totals.total}
              currency={formData.currency}
            />

            {/* Recent Orders */}
            <SalesOrderRecents />
          </div>
        </div>

        {/* Copy From Dialog */}
        <CopyFromDialog
          open={showCopyFromDialog}
          onOpenChange={setShowCopyFromDialog}
          targetType="sales-order"
          onCopy={handleCopyFrom}
          isLoading={createOrderMutation.isPending}
        />
      </div>
    </div>
  );
};

export const SalesOrderCreationPage: React.FC = () => {
  return (
    <QueryClientProvider client={queryClient}>
      <SalesOrderCreationContent />
    </QueryClientProvider>
  );
};